//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_BANGCONG_NHANVIEN_CHITIET
    {
        public int ID { get; set; }
        public Nullable<int> MAKYCONG { get; set; }
        public Nullable<int> MACTY { get; set; }
        public Nullable<int> MANV { get; set; }
        public string HOTEN { get; set; }
        public Nullable<System.DateTime> NGAY { get; set; }
        public string THU { get; set; }
        public string GIOVAO { get; set; }
        public string GIORA { get; set; }
        public Nullable<double> NGHIKHONGPHEP { get; set; }
        public Nullable<double> NGAYPHEP { get; set; }
        public Nullable<double> CONGNGAYLE { get; set; }
        public Nullable<double> GIOCONG { get; set; }
        public Nullable<double> NGAYCONG { get; set; }
        public Nullable<double> CONGCHUNHAT { get; set; }
        public string KYHIEU { get; set; }
        public string GHICHU { get; set; }
        public Nullable<double> NGAYCOM { get; set; }
        public Nullable<double> TIENCOM { get; set; }
        public Nullable<double> XANGXE { get; set; }
        public Nullable<double> THUETRO { get; set; }
        public Nullable<double> DOCHAI { get; set; }
        public Nullable<double> BHXH { get; set; }
        public Nullable<double> PHAT { get; set; }
        public Nullable<double> UNGLUONG { get; set; }
    }
}
