//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_LOAICONG
    {
        public int IDLOAICONG { get; set; }
        public string TENLOAICONG { get; set; }
        public Nullable<double> HESO { get; set; }
    }
}
